### PR TITLE
WIP: Mutex

### PR DESCRIPTION
**Pull request by kvaps**
Using mutex should protect structure from race-conditions during concurrent access to its fields.

I need to perform more tests but hopefully fixes https://github.com/piraeusdatastore/piraeus-ha-controller/issues/7

### CODE REVIEW

**Comment by WanzenBug** [comment]
Just FYI: I don't think a mutex will solve this issue. The updates to that struct are all done from a single thread/goroutine, Thats the big "for" loop that reconciles the state of the world. There may be some issue that causes it to miss some updates but I'm pretty sure a mutex won't help.

**Comment by kvaps** [comment]
@WanzenBug ok, afaik select is reading from the channels randomly, not consequentially. Since we're having too many channels with the updates, I guess it can cause such issues, isn't it?

https://github.com/piraeusdatastore/piraeus-ha-controller/blob/0dc2b4419533d2a294991da9976c3cfac6b8b6c9/pkg/hacontroller/controller.go#L143-L157

**Comment by WanzenBug** [comment]
I guess. But there should be at least 30/45 seconds between the PV being attached and the "fail" update arriving. I would be surprised if the VA and PVC updates didn't arrive in time.

Maybe there is some issue with the watch/resync logic that missed some updates.

**Comment by WanzenBug** [comment]
Since the rewrite, we are re-using the existing `k8s.io/client-go` objects that do local caching much better than us. So I'm closing this.

**Pull request closed without merging**
