### PR TITLE
build piraeus-ha-controller for arm64 and amd64

### PR DESCRIPTION
**Pull request by toelke**
The need for this change has been discussed in piraeusdatastore/piraeus#74

### CODE REVIEW

**Comment by WanzenBug** [comment]
@toelke do you want to apply the same triggers as in the other projects:
* build on PR, without push
* pushes on master + tags with push

**Comment by toelke** [comment]
As you wish :-D

**Comment by WanzenBug** [comment]
Thank you!

**Comment by toelke** [comment]
Sure. Thanks for your guidance!

**Pull request merged**
